// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { readSupabasePublishableKey, readSupabaseServiceRoleKey, readSupabaseUrl } from './env';

function createSupabaseAdminClient() {
  const SUPABASE_URL = readSupabaseUrl();
  const SUPABASE_SERVICE_ROLE_KEY = readSupabaseServiceRoleKey();
  const SUPABASE_FALLBACK_KEY = SUPABASE_SERVICE_ROLE_KEY || readSupabasePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_FALLBACK_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_FALLBACK_KEY ? ['SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Configure the production environment before starting Hype Delivery.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.warn("[Supabase] SUPABASE_SERVICE_ROLE_KEY is not configured. Server functions will use the publishable key and respect RLS.");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_FALLBACK_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
